file_Greetings = open("Greetings","wt")
file_Greetings.write("slam\n")
file_Greetings.write("you are good\n")
file_Greetings.write("How are you?\n")
file_Greetings.write("Are you ready to start your python class.\n")
file_Greetings.close()